databaseChangeLog:
  - changeSet:
      id: 1
      author: flexjob
      changes:
        - createTable:
            tableName: applications
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: job_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: employee_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: employer_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: applied_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp
                  constraints:
                    nullable: false

  - changeSet:
      id: 2
      author: flexjob
      changes:
        - createTable:
            tableName: application_messages
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: application_id
                  type: bigint
                  constraints:
                    nullable: false
                    foreignKeyName: fk_messages_application
                    references: applications(id)
              - column:
                  name: message_text
                  type: text
                  constraints:
                    nullable: false
              - column:
                  name: sender_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: sent_at
                  type: timestamp
                  constraints:
                    nullable: false
