spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/flexjob_review
    username: ${DB_USERNAME:flexjob}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
